"""Add user id to receipts

Revision ID: a5bd6234903d
Revises: fe204a2166e9
Create Date: 2025-03-20 17:58:02.674064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5bd6234903d'
down_revision: Union[str, None] = 'fe204a2166e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'receipts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='foreignkey')
    op.drop_column('receipts', 'user_id')
    # ### end Alembic commands ###
