"""Receipts

Revision ID: fe204a2166e9
Revises: 334316009044
Create Date: 2025-03-20 17:46:34.675545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe204a2166e9'
down_revision: Union[str, None] = '334316009044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('payment_type', sa.Enum('CASH', 'CASHLESS', name='paymenttype'), nullable=False),
    sa.Column('payment_amount', sa.Numeric(), nullable=False),
    sa.Column('total', sa.Numeric(), nullable=False),
    sa.Column('rest', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    sa.Enum('CASH', 'CASHLESS', name='paymenttype').drop(op.get_bind())
    # ### end Alembic commands ###
